#!/bin/bash
echo curl -d '{"interval":300}' http://10.1.10.21/cloud
curl -d '{"interval":300}' http://10.1.10.21/cloud

echo curl -d '{"url":"http://ws.radiothermostat.com/services.svc/StatIn"}' http://10.1.10.21/cloud
curl -d '{"url":"http://ws.radiothermostat.com/services.svc/StatIn"}' http://10.1.10.21/cloud
